# Generated by Django 6.0.5 on 2026-05-21 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000, message='Ano deve ser 2000 ou posterior.')]),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='mes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Mês deve ser entre 1 e 12.')]),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor_limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='O valor limite deve ser maior que zero.')]),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='O valor deve ser maior que zero.')]),
        ),
    ]
